### ISSUE TITLE
This is not JSON output

### ISSUE THREAD

**Issue by karan** [okor/whoiz#2]
http://whoiz.herokuapp.com/lookup.json?url=yahoo.com

> "\nWhois Server Version 2.0\n\nDomain names in the .com and .net domains can now be registered\nwith many different competing registrars. Go to http://www.internic.net\nfor detailed information.\n\n Server Name: YAHOO.COM.ZZZZZZZ.GET.ONE.MILLION.DOLLARS.AT.WWW.UNIMUNDI.COM\n IP Address: 209.126.190.70\n Registrar: PDR LTD. D/B/A PUBLICDOMAINREGISTRY.COM\n Whois Server: whois.PublicDomainRegistry.com\n Referral URL: http://www.PublicDomainRegistry.com\n\n Server Name: YAHOO.COM.ZZZZZZ.MORE.INFO.AT.WWW.BEYONDWHOIS.COM\n IP Address: 203.36.226.2\n Registrar: INSTRA CORPORATION PTY, LTD.\n Whois Server: whois.instra.net\n Referral URL: http://www.instra.com\n\n Server Name: YAHOO.COM.ZZZZZ.GET.LAID.AT.WWW.SWINGINGCOMMUNITY.COM\n IP Address: 69.41.185.196\n Registrar: TUCOWS DOMAINS INC.\n Whois Server: whois.tucows.com\n Referral URL: http://domainhelp.opensrs.net\n\n Server Name: YAHOO.COM.ZOMBIED.AND.HACKED.BY.WWW.WEB-HACK.COM\n IP Address: 217.107.217.167\n Registrar: DOMAINCONTEXT, INC.\n Whois Server: whois.domaincontext.com\n Referral URL: http://www.domaincontext.com\n\n Server Name: YAHOO.COM.VN\n Registrar: MELBOURNE IT, LTD. D/B/A INTERNET NAMES WORLDWIDE\n Whois Server: whois.melbourneit.com\n Referral URL: http://www.melbourneit.com\n\n Server Name: YAHOO.COM.VIRGINCHASSIS.COM\n IP Address: 66.218.71.205\n Registrar: DOMAIN.COM, LLC\n Whois Server: whois.domain.com\n Referral URL: http://www.domain.com\n\n Server Name: YAHOO.COM.TWIXTEARS.COM\n IP Address: 66.218.71.205\n Registrar: DOMAIN.COM, LLC\n Whois Server: whois.domain.com\n Referral URL: http://www.domain.com\n\n Server Name: YAHOO.COM.TW\n Registrar

This isn't JSON. Any plans on fixing this?

**Comment by okor** [comment]
Good news! Thanks to my most recent code crime, whoiz now returns actual JSON.
